INSERT INTO PUBLIC.CURSO (CATEGORIA, NOME) VALUES('programação', 'java');
INSERT INTO PUBLIC.CURSO (CATEGORIA, NOME) VALUES('programação', 'python');
INSERT INTO PUBLIC.CURSO (CATEGORIA, NOME) VALUES('bi', 'powerbi');

INSERT INTO PUBLIC.USUARIO (EMAIL, NOME, SENHA) VALUES('user1@email.com', 'Usuario 1', '$2a$10$R5/Uy8NH22TvcioWiWWtB.RZbSKZ46L0Nvj6Y1Ngwq1G22AqXcvP2'); -- 123456

INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-07-25 18:00:00', 'Queria um script' ,'NAO_RESPONDIDO', 'Dúvida 1', 1, 1);
INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-07-26 18:00:00', 'Esse curso não tem os arquivos' ,'NAO_RESPONDIDO', 'Dúvida 2', 1, 2);
INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-07-27 18:00:00', 'Esse curso tem paginação?' ,'NAO_RESPONDIDO', 'Dúvida 2', 1, 2);
INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-07-28 18:00:00', 'Criação de nova página' ,'NAO_RESPONDIDO', 'Dúvida 2', 1, 2);
INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-07-29 18:00:00', 'Topico 1 - novo item 1' ,'NAO_RESPONDIDO', 'Dúvida 2', 1, 2);
INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-07-30 18:00:00', 'Topico 1 - novo item 2' ,'NAO_RESPONDIDO', 'Dúvida 2', 1, 2);
INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-07-31 18:00:00', 'Topico 1 - novo item 3' ,'NAO_RESPONDIDO', 'Dúvida 2', 1, 2);
INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-08-01 18:00:00', 'Topico 1 - novo item 4' ,'NAO_RESPONDIDO', 'Dúvida 2', 1, 2);
INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-08-02 18:00:00', 'Topico 1 - novo item 5' ,'NAO_RESPONDIDO', 'Dúvida 2', 1, 2);
INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-08-03 18:00:00', 'Topico 1 - novo item 6' ,'NAO_RESPONDIDO', 'Dúvida 2', 1, 2);
INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-08-04 18:00:00', 'Topico 1 - novo item 7' ,'NAO_RESPONDIDO', 'Dúvida 2', 1, 2);
INSERT INTO PUBLIC.TOPICO (DATA_CRIACAO, MENSAGEM, STATUS, TITULO, AUTOR_ID, CURSO_ID) VALUES('2019-08-05 18:00:00', 'Topico 1 - novo item 8' ,'NAO_RESPONDIDO', 'Dúvida 2', 1, 2);

INSERT INTO PUBLIC.RESPOSTA (DATA_CRIACAO, MENSAGEM, SOLUCAO, AUTOR_ID, TOPICO_ID) VALUES('2019-07-25 20:00:00', 'Tenta novamente', false, 1, 1);
INSERT INTO PUBLIC.RESPOSTA (DATA_CRIACAO, MENSAGEM, SOLUCAO, AUTOR_ID, TOPICO_ID) VALUES('2019-07-25 19:00:00', 'Faça na mão', false, 1, 1);
INSERT INTO PUBLIC.RESPOSTA (DATA_CRIACAO, MENSAGEM, SOLUCAO, AUTOR_ID, TOPICO_ID) VALUES('2019-07-25 18:00:00', 'Espere a próxima aula', false, 1, 2);
